Repository maxitg/PostTagSystem, pull requests merged in 2021-03, with the labels that each got.

#17 Feature/initialize parameters
  libPostTagSystem/PostTagSearcher.hpp
Labels: enhancement

#18 Searcher API tests
  libPostTagSystem/PostTagSearcher.cpp
  libPostTagSystem/PostTagSearcher.hpp
  libPostTagSystem/test/PostTagSearcher_test.cpp
Labels: test

#19 Max tape length limit
  libPostTagSystem/PostTagHistory.cpp
  libPostTagSystem/PostTagHistory.hpp
  libPostTagSystem/PostTagSearcher.cpp
  libPostTagSystem/WolframLanguageAPI.cpp
  libPostTagSystem/test/PostTagSearcher_test.cpp
  libPostTagSystem/test/PostTagSystem_test.cpp
Labels: enhancement

#21 Searcher checkpoints
  libPostTagSystem/PostTagHistory.cpp
  libPostTagSystem/PostTagHistory.hpp
  libPostTagSystem/PostTagSearcher.cpp
  libPostTagSystem/test/PostTagSearcher_test.cpp
Labels: enhancement

#22 Time constraint
  libPostTagSystem/PostTagHistory.cpp
  libPostTagSystem/PostTagHistory.hpp
  libPostTagSystem/PostTagSearcher.cpp
  libPostTagSystem/PostTagSearcher.hpp
  libPostTagSystem/test/PostTagSearcher_test.cpp
Labels: enhancement

#24 Shared trie
  libPostTagSystem/CheckpointsTrie.cpp
  libPostTagSystem/CheckpointsTrie.hpp
  libPostTagSystem/PostTagHistory.cpp
  libPostTagSystem/PostTagHistory.hpp
  libPostTagSystem/PostTagSearcher.cpp
  libPostTagSystem/PostTagSearcher.hpp
  libPostTagSystem/test/CheckpointsTrie_test.cpp
  libPostTagSystem/test/PostTagSearcher_test.cpp
Labels: enhancement

#16 Tag searcher CLI executable
  .circleci/config.yml
  .dockerignore
  CLI/CMakeLists.txt
  CLI/arguments.cpp
  CLI/arguments.hpp
  CLI/files/PostTagCribFile.cpp
  CLI/files/PostTagCribFile.hpp
  CLI/files/PostTagFile.hpp
  CLI/files/PostTagFileReader.cpp
  CLI/files/PostTagFileReader.hpp
  CLI/files/PostTagFileWriter.cpp
  CLI/files/PostTagFileWriter.hpp
  CLI/files/PostTagInitFile.cpp
  CLI/files/PostTagInitFile.hpp
  CLI/files/PostTagResultFile.cpp
  CLI/files/PostTagResultFile.hpp
  CLI/main.cpp
  CMakeLists.txt
  Dockerfile
  FileFormats/CribFile.wl
  FileFormats/InitFile.wl
  FileFormats/PostTagFileFormats.wl
  FileFormats/README.md
  FileFormats/ResultFile.wl
  FileFormats/SampleFiles/crib1.postcrib
  FileFormats/SampleFiles/init1.postinit
  FileFormats/SampleFiles/result1.postresult
  FileFormats/SampleFiles/result2.postresult
  FileFormats/Utility.wl
  libPostTagSystem/PostTagSearcher.hpp
  lint.sh
Labels: enhancement

#28 Fix last tape
  libPostTagSystem/PostTagSearcher.cpp
  libPostTagSystem/test/PostTagSearcher_test.cpp
Labels: weed

#29 Fix macOS just-in-time compilation
  DevUtils/BuildLibPostTagSystem.m
Labels: weed

#30 Checkpoints every event multiple
  libPostTagSystem/PostTagHistory.cpp
  libPostTagSystem/PostTagHistory.hpp
  libPostTagSystem/PostTagSearcher.cpp
  libPostTagSystem/PostTagSearcher.hpp
  libPostTagSystem/WolframLanguageAPI.cpp
  libPostTagSystem/test/PostTagSystem_test.cpp
Labels: enhancement
